/*
 Copyright 2014 OpenMarket Ltd

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

#import <Foundation/Foundation.h>

@interface MXReceiptData : NSObject <NSCoding, NSCopying>

/**
 The event id.
 */
@property (nonatomic, nonnull) NSString *userId;

/**
 The event id.
 */
@property (nonatomic, nonnull) NSString *eventId;

/**
 The thread id. This value shouldn't be nil as per https://github.com/matrix-org/matrix-spec-proposals/pull/3771 but you can set it to nil for unthreaded event.
 */
@property (nonatomic, nullable) NSString *threadId;

/**
 The timestamp in ms since Epoch generated by the origin homeserver when it receives the event
 from the client.
 */
@property (nonatomic) uint64_t ts;

@end
