# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "MatrixSDK" do
pod 'AFNetworking', '~> 2.4.1'
pod 'Mantle', '~> 1.5'
end

target "MatrixSDKTests" do

end

