name: Crypto Tests CI

on:
  # Triggers the workflow on any pull request and push to develop
  push:
    branches: [ develop ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  crypto-tests:
    name: Crypto Tests with Synapse
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      # Cache for python env for Synapse
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      # Cache for Xcode env
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Start synapse server
        run: |
          python3 -m venv .synapse
          source .synapse/bin/activate
          pip install synapse matrix-synapse
          curl -sL https://raw.githubusercontent.com/matrix-org/synapse/develop/demo/start.sh \
            | sed s/127.0.0.1/0.0.0.0/g | bash -s -- "--no-rate-limit"

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Main step
      - name: Crypto tests
        run: bundle exec fastlane test testplan:CryptoTests

      # Store artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: report.html
          path: build/test/report.html
      - uses: actions/upload-artifact@v2
        with:
          name: report.junit
          path: build/test/report.junit
      - uses: actions/upload-artifact@v2
        with:
          name: MatrixSDK-macOS.xcresult
          path: build/test/MatrixSDK-macOS.xcresult/
